// Generate skills briefs from SKILL.md files.
// Reads each skills/<name>/SKILL.md, extracts the YAML frontmatter name
// and first description line, and writes to src/skills-briefs.ts.
// This ensures the MCP server has up-to-date skill briefs.

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SKILLS_DIR = path.resolve(__dirname, "..", "skills");
const OUTPUT_FILE = path.resolve(__dirname, "..", "src", "skills-briefs.ts");

interface SkillBrief {
  name: string;
  description: string;
  brief: string;
}

function extractFrontmatter(content: string): { name?: string; description?: string } {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};

  const frontmatter: Record<string, string> = {};
  const lines = match[1].split("\n");
  for (const line of lines) {
    const kv = line.match(/^(\w+):\s*(.+)/);
    if (kv) {
      frontmatter[kv[1]] = kv[2].trim();
    }
  }
  return frontmatter;
}

function extractBrief(content: string): string {
  // Extract first paragraph after frontmatter
  const afterFrontmatter = content.replace(/^---\n[\s\S]*?\n---\n*/, "").trim();
  const firstLine = afterFrontmatter.split("\n")[0].trim();
  // Clean up markdown formatting
  return firstLine
    .replace(/^#+\s*/, "")
    .replace(/\*\*/g, "")
    .trim();
}

function main() {
  const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });
  const skills: SkillBrief[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const skillDir = path.join(SKILLS_DIR, entry.name);
    const skillFile = path.join(skillDir, "SKILL.md");

    if (!fs.existsSync(skillFile)) {
      console.warn(`⚠ SKILL.md not found for ${entry.name}`);
      continue;
    }

    const content = fs.readFileSync(skillFile, "utf-8");
    const fm = extractFrontmatter(content);
    const brief = extractBrief(content);

    const name = fm.name || entry.name;
    const fullName = name.startsWith("co-") ? name : `co-${name}`;

    skills.push({
      name: fullName,
      description: fm.description || "",
      brief,
    });
  }

  // Generate TypeScript
  const lines = [
    "// Auto-generated by scripts/generate-skills.ts — DO NOT EDIT",
    "// Generated from skills/*/SKILL.md",
    "",
    "export interface SkillBrief {",
    "  name: string;",
    "  description: string;",
    "  brief: string;",
    "}",
    "",
    "export const SKILL_BRIEFS: Record<string, SkillBrief> = {",
  ];

  for (const skill of skills) {
    lines.push(`  "${skill.name}": {`);
    lines.push(`    name: "${skill.name}",`);
    lines.push(`    description: ${JSON.stringify(skill.description)},`);
    lines.push(`    brief: ${JSON.stringify(skill.brief)},`);
    lines.push(`  },`);
  }

  lines.push("};");
  lines.push("");

  fs.writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");
  console.log(`✅ Generated ${skills.length} skill briefs → ${OUTPUT_FILE}`);
}

main();