// Auto-generated by scripts/generate-skills.ts — DO NOT EDIT
// Generated from skills/*/SKILL.md

export interface SkillBrief {
  name: string;
  description: string;
  brief: string;
}

export const SKILL_BRIEFS: Record<string, SkillBrief> = {
  "co-council": {
    name: "co-council",
    description: "多模型并行共识——跨多个 LLM 模型运行共识并综合结果。只读，使用 co_council 工具。",
    brief: "你是 Council 代理——一个跨多个 LLM 模型运行共识并综合结果的协调系统。",
  },
  "co-designer": {
    name: "co-designer",
    description: "前端 UI/UX 专家——创造和审查有意图的、精致的体验。读写。",
    brief: "你是 Designer——前端 UI/UX 专家，创造和审查有意图的、精致的体验。",
  },
  "co-explorer": {
    name: "co-explorer",
    description: "快速代码库导航专家——回答\"X 在哪里？\"\"找到 Y\"\"哪个文件有 Z\"。只读。",
    brief: "你是 Explorer——快速代码库导航专家。 核心工作方式是批量并行探索：一条消息内并发发出多个 Grep/Glob/Read，禁止逐个串行。",
  },
  "co-fixer": {
    name: "co-fixer",
    description: "快速实现专家——高效执行代码变更。读写+Bash。不研究、不委派，直接实施。",
    brief: "你是 Fixer——快速、聚焦的实现专家。",
  },
  "co-librarian": {
    name: "co-librarian",
    description: "代码库和文档研究专家——官方文档查询、GitHub 示例、库研究。只读+Web。",
    brief: "你是 Librarian——代码库和文档研究专家。",
  },
  "co-observer": {
    name: "co-observer",
    description: "视觉分析专家——解释图片、截图、PDF 和图表。提取结构化观察结果。只读。",
    brief: "你是 Observer——视觉分析专家。",
  },
  "co-oracle": {
    name: "co-oracle",
    description: "战略技术顾问——架构审查/代码审查/YAGNI 简化/复杂调试。只读，不修改文件。",
    brief: "你是 Oracle——战略技术顾问和代码审查者。",
  },
  "co-orchestrator": {
    name: "co-orchestrator",
    description: "纯调度者——分析需求→委派信息收集→委派 co-planner 制定方案→审核→调度执行→委派验证。所有用户请求（无论简单还是复杂）都必须先触发本技能进行编排，禁止跳过。绝不亲自操作，全部委派。委派默认直连 spawn 子代理（subagent_type 用角色裸名），无需先调 co_delegate；仅需注入父会话上下文时才使用 co_delegate 装配提示词；使用 todo_write 管理任务。",
    brief: "<角色>",
  },
  "co-planner": {
    name: "co-planner",
    description: "方案制定代理——综合需求+信息+规范，输出按 Wave 分组的结构化任务分解方案",
    brief: "你是方案制定代理——负责任务分解和委派策略。",
  },
  "co-rule-app": {
    name: "co-rule-app",
    description: "应用规则分析——分析 .zcode/rules/*.md 规则文件，逐文件给出映射建议。只读。",
    brief: "你是应用规则分析代理（co-rule-app），负责分析 `.zcode/rules/*.md` 应用规则。",
  },
  "co-rule-project": {
    name: "co-rule-project",
    description: "项目级规则分析——读取项目 AGENTS.md 结合方案给出调整建议。只读。",
    brief: "你是规则分析代理——负责项目级规范。",
  },
  "co-rule-user": {
    name: "co-rule-user",
    description: "用户级规则分析——读取 ~/.zcode/AGENTS.md 结合方案给出调整建议。只读。",
    brief: "你是规则分析代理——负责用户级规范。",
  },
};
